services:
  rtmp-server:
    image: alfg/nginx-rtmp
    container_name: s23-rtmp
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx/rtmp.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - rave-net

  streamer:
    environment:
      - OUTPUT_MODE=rtmp
      - RTMP_URL=rtmp://rtmp-server:1935/live/stream
    depends_on:
      - rtmp-server

networks:
  rave-net:
    driver: bridge
